### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by RealMahmoud** [idena-network/idena-web#1]
![image](https://user-images.githubusercontent.com/61373609/95830957-b6bb7400-0d38-11eb-9441-a8a18bf90e06.png)
why this bug occurred ?

**Comment by RealMahmoud** [comment]
i coded this little code and it worked but i think something missing 
`const express = require('express');
const bodyParser = require('body-parser');

const {
    createProxyMiddleware
} = require('http-proxy-middleware');
const app = express();
app.use(bodyParser.json());
const PORT = 4000;
const HOST = "0.0.0.0";
const API_SERVICE_URL = 'http://localhost:9009'
const methods = [
    'dna_identity',
    'dna_ceremonyIntervals',
    'dna_epoch',
    'dna_isValidationReady',
    'dna_wordsSeed',
    'dna_getBalance',
    'flip_getRaw',
    'flip_getKeys',
    'flip_shortHashes',
    'flip_longHashes',
    'flip_privateEncryptionKeyCandidates',
    'flip_sendPrivateEncryptionKeysPackage',
    'flip_sendPublicEncryptionKey',
    'bcn_syncing',
    'bcn_getRawTx',
    'bcn_sendRawTx',
]
app.get('', (req, res, next) => {
    res.send('Hello , please donate > 0xe151841d51527e5e8261a32ea78074e93224e882');
});
app.use('', createProxyMiddleware({
    target: API_SERVICE_URL,
    changeOrigin: true,
    secure : true,
    onProxyReq(proxyReq, req, res) {
        if (methods.indexOf(req.body.method) === -1) {
            proxyReq.destroy()
            res.status(403).send('Method fobidden')
            return
        }
        
    }
}));


app.listen(PORT, HOST, () => {
    console.log(`Starting Proxy at ${HOST}:${PORT}`);
});`
however i also tried using using 0.0.0.0 as rpcaddr and it exposed the port to the internet and it also didn't work on the app but worked on the normal client

**Comment by midenaio** [comment]
`https://` is required for the shared node connection

**Comment by RealMahmoud** [comment]
![image](https://user-images.githubusercontent.com/61373609/95880836-387ec200-0d78-11eb-81df-065258e9c85c.png)

**Comment by RealMahmoud** [comment]
i have fixed the https thing and now i got this
