### ISSUE TITLE
Problems with Validation (local Node)

### ISSUE THREAD

**Issue by DragonDev1906** [idena-network/idena-web#105]
Hello,
I had some problems during the last validation session and this seems like the right place to put them.

I got a message saying that I need to sync my time, but when I clicked on it it showed the same time as my system (less than 1sec offset), so that shouldn't be the issue either.

# Problem description
- Images are not loaded and in addition to not being able to see the images I was also unable to select left or right:
![2021-09-01_15:31:06](https://user-images.githubusercontent.com/8270201/131689321-b800e280-7d56-49cc-a39e-ed443de7eea1.png)
- After that (in the 30min validation session) most Flips did load, but the keywords didn't (in the earlier ones I could see the images but it kept showing the `getting keywords` message:
![2021-09-01_15:50:12](https://user-images.githubusercontent.com/8270201/131689587-7c467c0a-188b-4d2c-a201-06aee1025e69.png)

This effectively resulted in me being unable to do anything in the validation session.

# My setup
## app.idena.io
- Arch Linux
- Firefox (91.0.2)
- Incognito Mode: No
- Extensions:
    - NoScript: Loaded but all (5) Domains where allowed to execute JavaScript
    - uBlock Origin: Disabled after I started seeing issues
    - Vue Devtools
    - MetaMask
- Node: `http://127.0.0.1:9009`

## Node
- In a VirtualMachine on the same host (NAT, port's are forwarded)
- Manjaro Linux (installed using the AUR)
- idena-go version 0.26.7
- Fully synchronized
- API key taken from `api.key`

# Logs
## Node
```
ERROR[09-01|13:46:22.987] error while writing to stream            id=QmZSyy2MTy1yrHDcTKGqyKpFbudwMNHHuFJxyeZ9SXKCbE err="closed stream"
INFO [09-01|13:46:22.987] Peer disconnected                        id=QmZSyy2MTy1yrHDcTKGqyKpFbudwMNHHuFJxyeZ9SXKCbE
```
with different peer IDs, usually soon after a peer connected (not the case for all peers)

```
WARN [09-01|13:30:49.824] GetEncryptedPrivateFlipKey: public flip key is missing address=0x26C958225042e7Ab1dEc1CD6376Ac981B2434c5b
```

With the exception of those two types there where no other Errors or Warnings I could find. I needed I can also send the complete log file, but I don't think that is necessary. 

## app.idena.io
The log file (settings/General/Validation Logs) only contains the word `null` and is thus of no help at all.

## JavaScript console output
I unfortunately didn't save a screenshot/copy of the output, but here are the Error messages it contained:
```
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: https://marketplace.idena.io/api/key/check?key=<my-api-key>
Zeile Nr. 1, Spalte 1:
```
That URL returns a 400 Bad Request with the body `failed to retrieve api key`. Also, I do not understand why my api key would be send to marketplace.idena.io if I'm hosting my own node. This error is displayed (in the JavaScript console, F12) as soon as I entered my Password.

```
Sicherheitsfehler: Inhalt auf https://app.idena.io/validation darf keine Daten von blob:https://app.idena.io/e803ccc4-9ef3-49cf-a61f-e362bf39edbc laden.
```
With different UIDs as the path.

**Comment by thanhtantran** [comment]
You install idena-go and idena-web on a same machine?

**Comment by DragonDev1906** [comment]
idena-go ran in a VM, while I was using idena-web on the PC that was running the VM.

**Comment by midenaio** [comment]
Normally you can not use `https://app.idena.io` with the `http://localhost:9009` node connection. Although if you still want to please check this out for more details: https://github.com/idena-network/idena-desktop/issues/411
