### ISSUE TITLE
Show next date in unambigous format

### ISSUE THREAD

**Issue by abitrolly** [idena-network/idena-web#106]
I've just missed the validation, which I thought will be on 9th, because Idena shows date in American format, where the first digit is not a day, but a month.

![image](https://user-images.githubusercontent.com/8781107/132142764-5eb251e4-ff1c-4bcb-b4ac-341566b2bd97.png)

I wouldn't miss it if the date was in ISO format, like 2021-09-02 and there was a more prominent header somewhere with content like "two weeks and three days till the next validation".

Now it seems that I need another invite for 0x806c2577f1d1d1140107b67b24405353fea169eb because of the missed check.

**Comment by pocoloko** [comment]
It actually shows the date/time using whatever your PC's locale is set to, so this is on your end, your PC or browser is set to display it like that.

**Comment by abitrolly** [comment]
@pocoloko this is how my PC is configured to show date/time.

![image](https://user-images.githubusercontent.com/8781107/132221000-3bd3df5c-5229-4ffd-afe8-b662c765a171.png)

**Comment by abitrolly** [comment]
The same goes for terminal apps.

![image](https://user-images.githubusercontent.com/8781107/132221182-6eaa3963-46c6-4d5a-b2f1-bc04f15fd436.png)

**Comment by pocoloko** [comment]
Someone with more knowledge on how the date is displayed in the web app will have to reply to you, it could be some kind of bug. How does the Next Validation date on www.idena.io show up for you?

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/132222949-5c6a8cd9-337e-4c2e-918a-70c3174868dc.png)

**Comment by pocoloko** [comment]
interesting, not sure what OS you're using, but you should check the Date Format under Regional Settings

**Comment by abitrolly** [comment]
You were right. There are also `Regions & Language` settings, where United States (English) was selected for Formats.

![image](https://user-images.githubusercontent.com/8781107/132232013-43fef50a-2609-41db-96df-400192e35d33.png)

The closest to unambiguous is either Denmark.

![image](https://user-images.githubusercontent.com/8781107/132232741-f334b47a-9096-43e3-93fc-c0edc2f1d935.png)

Or Philippines.

![image](https://user-images.githubusercontent.com/8781107/132232790-c4801594-3798-49e0-a305-13820112d398.png)

The OS is Fedora 34.

**Comment by rioda-org** [comment]
For Windows, it depends solely on your browser settings/instalation
- in Chrome, you can change it inside settings
- for Firefox, you can't change it, it depends on the installation you chose, for me dd.mm.yyyy is ok, so I go for EN_GB firefox instalation to have good time format.

**Comment by aidenaio** [comment]
validation date formatted according to user locale https://github.com/idena-network/idena-web/blob/937dfcb1dccce6243a4f151838a1c33b9256bbeb/shared/utils/utils.js#L90

`[]` - no specific locales defined, which can be `['en-us, 'en-gb'] for instance

so it all depends on your browser/os setup

**Comment by abitrolly** [comment]
How about using humanreadable notation? Like `15 days, at 15:00 +3`

**Comment by mnz2000** [comment]
I also have the US format as default, and it is totally misleading. It may be caused by my browser language settings (I use English as default), but it doesn't really matter. What matters is that the US format is shown to many regular users for whom it is not their native format.

Idena cannot expect browser/os to behave (because they don't). Especially since the date of next validation date is such an important thing in Idena!

I second abitrolly's suggestion above and use a notation like "X d Y h Z m Q s to next validation". And showing this in addition to the (poorly-formatted) date. Exactly as is done on the https://idena.io main page.
