### ISSUE TITLE
Bad training validation data

### ISSUE THREAD

**Issue by sekisanchi** [idena-network/idena-web#124]
Looks like current training flips are chosen from previous validations.  But because of farms and coordinated attacks, those are contaminated to allow them through, and inappropriate examples may be set.  Here's some bad flip examples shown as proper examples. Probably much larger committee should evaluate the validity of the flips for the training, or should be chosen manually by experts.    

1.  The thickness of the red bands imply the sequence of the three frames.  It should be bad flip.

![DiskCondition](https://user-images.githubusercontent.com/1669550/134808806-9f7c2cb5-90b2-4852-a9b5-134fd34faaa1.jpg)

2. The number of percussions in the drum sets enumerates the sequence,  1-5-9-10+  It should be bad flip.
  
![Drums](https://user-images.githubusercontent.com/1669550/134808827-80334650-beb0-4f1d-b3fd-3325a1129028.jpg)

**Comment by midenaio** [comment]
Training validation flips have been updated. Thanks for your input.
