### ISSUE TITLE
When renting new node, old URL is not cleared from Settings

### ISSUE THREAD

**Issue by abitrolly** [idena-network/idena-web#140]
I rented new node https://node.idena.to because old one expired. The node is listed at https://app.idena.io/node/rent as online, but web app showed that the node is unavailable until I went to settings and changed Shared node URL from old value to a new one.

![image](https://user-images.githubusercontent.com/8781107/136782142-10dc3127-24bb-4df6-ab85-f65e3fe8358c.png)

Originally reported here  https://www.reddit.com/r/Idena/comments/pylm3s/rented_node_is_offline_but_in_the_list/

**Comment by rioda-org** [comment]
Can confirm this happened with another user. Can't remember which browser or OS it was.

**Comment by midenaio** [comment]
The issue has been fixed. If you still have this problem, please reopen this issue and we'll investigate it.
