### ISSUE TITLE
Issue with the ordering of flips?

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-web#171]
member @Mahdikomaiha on TG
"idena scan says I have 5/6 even though the explorer says I got all of them right"
https://scan.idena.io/identity/0x2427855b318320b17b3d9e12a1bdcdee6d40d2b1/epoch/78/validation

[validation-77-0x2427855b318320b17b3d9e12a1bdcdee6d40d2b1.txt](https://github.com/idena-network/idena-web/files/7574817/validation-77-0x2427855b318320b17b3d9e12a1bdcdee6d40d2b1.txt)

node used
https://node.idena.cyou

**Comment by rioda-org** [comment]
Also, it would be usefull if web app logs could write shared node that member used.

**Comment by hlolve** [comment]
There was a problem getting flips and backup was used

This flip had problems

https://scan.idena.io/flip/bafkreicbq43oh7jepvwpyeyrapa6vbioda5ugry4isfnyz42urs2f3kmle

Was received for this other ID 

https://scan.idena.io/identity/0x5247911EAD3617b47B942437c00e4aD3258b43fD/epoch/78/validation#shortAnswers

and also has 3/6 but 4/6 OK

---------------------------------------------------

This other flip had problems

https://scan.idena.io/flip/bafkreiezboz2qzdz5joixvvmgh66l5bj6fdxriere45ld4tqbaopiocd2a

Was received for this other ID 

https://scan.idena.io/identity/0x6A37Ae7D6f048D94eaBF4d7A5d4ad48A7430DC3A/epoch/78/validation#shortAnswers

But is not in list of Validation answers

**Comment by rioda-org** [comment]
Here are logs from one more users, same issues, same node
[validation-77-0xd5f6fde1be4c73ef6d063012a9fe17dbf08c9b62.txt](https://github.com/idena-network/idena-web/files/7591285/validation-77-0xd5f6fde1be4c73ef6d063012a9fe17dbf08c9b62.txt)
[validation-77-0x4c0e8cf0dda97a7cdd8312fed373b0f8425d72fc.txt](https://github.com/idena-network/idena-web/files/7591286/validation-77-0x4c0e8cf0dda97a7cdd8312fed373b0f8425d72fc.txt)

**Comment by hlolve** [comment]
> Here are logs from one more users, same issues, same node [validation-77-0xd5f6fde1be4c73ef6d063012a9fe17dbf08c9b62.txt](https://github.com/idena-network/idena-web/files/7591285/validation-77-0xd5f6fde1be4c73ef6d063012a9fe17dbf08c9b62.txt) [validation-77-0x4c0e8cf0dda97a7cdd8312fed373b0f8425d72fc.txt](https://github.com/idena-network/idena-web/files/7591286/validation-77-0x4c0e8cf0dda97a7cdd8312fed373b0f8425d72fc.txt)

Both files are from ID 0xd5f6fde1be4c73ef6d063012a9fe17dbf08c9b62. In there also had problems to load flips. You have to see shared node's logs

**Comment by midenaio** [comment]
The blockchain explorer has been fixed. Now it correctly displays the score 0 for the non-answered flips. The problem may happen if the user does not give an answer to mandatory flips that are available to the rest of the network. 

The root problem is related to the flips availability issue on the shared node `node.idena.cyou` . We plan to make some fixes to improve communication between shared nodes.
