### ISSUE TITLE
Problem with idena bridge. 

### ISSUE THREAD

**Issue by adityaindra68** [idena-network/idena-web#172]
I have a problem with the idena bridge, the transaction has been processed and the balance on my idena app has decreased but the idena balance is not showing on my metamask account, I need help urgently. Thanks in advance. 

Transaction links:
https://bridge.idena.io/operation/ea030129-ec7f-4b47-b0df-e5d25f13d579

**Comment by aidenaio** [comment]
please use support for such a requests
