### ISSUE TITLE
Flip images are tiny on phone screen

### ISSUE THREAD

**Issue by mnz2000** [idena-network/idena-web#185]
Two screenshot from my OnePlus 7 phone today at the end of this post. The flip images are so tiny, that I had absolutely no way of making anything out of them. Failed the validation with 1/6. (Please note that the images here show so large that you can actually make out their contents - imagine the full image shrinked to the size of a phone screen).

Two suggestions based on this:

1. Fix the image size.
2. Allow the user to zoom in/out on the app. With zooming, it would have been possible to complete the validation (even if cumbersome). Especially because the phone layout seems very much work-in-progress at the moment, i.e. there is unnecessary panning left/right when all elements don't fit the screen. It doesn't make any sense to disallow zooming.

![Screenshot_20211211-153032](https://user-images.githubusercontent.com/13187064/145680687-4e7890ef-8492-40a7-b230-18fb36ea4eb1.jpg)
![Screenshot_20211211-153441](https://user-images.githubusercontent.com/13187064/145680688-1bff9645-46d2-4a3c-8165-70d040579d33.jpg)

**Comment by mnz2000** [comment]
Training validation looks completely fine on my phone, by the way. It seems like it was only the real validation that was screwed up.

**Comment by ridenaio** [comment]
Hi, please provide your idena address.

**Comment by ridenaio** [comment]
Please open the issue again if the problem still exists.
