### ISSUE TITLE
Suggestion: Add ssh tunnel connection capability

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-web#195]
This option would be usefull for users who run their node on VPS so they can connect Web App to it, without proxy+domain+ssl certificate.

**Comment by ridenaio** [comment]
Hi, users who run their own node on VPS can open SSH tunnel using putty or another programs and use `http://localhost:port` as a node URL. Browsers do not restrict requests from `https` to `localhost`

**Comment by rioda-org** [comment]
Hi, from pc, it's not as problematic as it is to make ssh tunnel from mobile phone (or to make an easy guide for it). But currently there are less interested people who want to run their node on vps so never mind.
