### ISSUE TITLE
Wrong (old) url after renting node

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-web#210]
Hi, one member passed validation and after that rented my node, app showed offline status
Url is wrong, api key is ok
Client: Chrome browser on the laptop

![image](https://user-images.githubusercontent.com/37978870/153720605-9464d8c7-690a-4595-99db-333a251cd406.png)

**Comment by ridenaio** [comment]
Hi, please re-open this issue if the problem still exists. This should be already fixed.
