### ISSUE TITLE
error when importing Private key into Metamask - "Expected private key to be an Uint8Array with length 32"

### ISSUE THREAD

**Issue by lyricalpolymath** [idena-network/idena-web#221]
Hi 
I tried importing the autogenerated private key into Metamask but I get this error
"Expected private key to be an Uint8Array with length 32"
I tried with and without a prefixing "0x"

I know this might be more a Metamask error.. but maybe you have some pointers.
is it useful at all to import it into Metamask?

thanks

**Comment by Ophelia45** [comment]
I will suggest you contact metamask support and click on the live chat message logo to talk with a Developer from metamask through their live chat Developers forum to help you sort this issue out right away. https://metamaskzendesk.helpsconnect.live/#

**Comment by ridenaio** [comment]
Metamask expects raw private key, but now you cannot export your raw key from web application.

If you use desktop app with build-in node, or just VPS node, you can find your raw private key in `datadir/keystore/nodekey` file
