### ISSUE TITLE
Human Stuck: Please display keywords so we can say if they are missing

### ISSUE THREAD

**Issue by gilescope** [idena-network/idena-web#222]
"One/both keywords are not relevant"

![Screenshot(32)](https://user-images.githubusercontent.com/803976/159153938-7b0db47d-d9fc-4e75-8dc0-406b7bbc849b.png)

- Maybe I am missing something but on linux using firefox and chrome how are you meant to know what the keywords are? The idea is good but you need to give the human enough details to be able to pass. Or are we meant to guess the keywords and then guess that it is missing? I couldn't even find them in the html source...

I would like to pass and prove I am human but sadly it seems not possible at the moment. What am I missing and how can we make it a better experience for the next person?

**Comment by ridenaio** [comment]
Hi, this is the `short session`, where you just need to solve flips. Flip keywords are available only during the `long session`.
