### ISSUE TITLE
Scheduled transactions pop up

### ISSUE THREAD

**Issue by Zen-44** [idena-network/idena-web#265]
If one of your scheduled transactions is ready to be sent to the network the pop-up will appear at almost every click (when going through the menu). 
I think this could be made more friendly by limiting how many times the pop-up appears. If the user clicks 'Not now' the pop-up should not appear anymore (at least during that specific session).

**Comment by ridenaio** [comment]
Hi! Could you please give an example, when user needs to click 'Not now' instead of sending the transaction? So, are there any cases, when you do not want to send scheduled tx ?
