### ISSUE TITLE
Spots on market place

### ISSUE THREAD

**Issue by kapo89star** [idena-network/idena-web#274]
Can you fix on some way so soon as you sell key you go on last spot on market place. 
Lot of people complain about system so please can you fix that and make shared node providers happy. 
My idea is soon as you sell 1 key you go to last place on page if its possible.
Reason people who have less keys they are on last place on page and they think they are get discriminated, so they sell less keys then people who are on top. 
Thanks

**Comment by Zen-44** [comment]
I think this is a good idea! This way providers will have their turn to be on top of the list. Not sure if putting someone last after a key is bought is the solution, but some kind of rotation could definitely be implemented.

**Comment by kapo89star** [comment]
Also people who are not online need to go on last place.
How I saw lot of providers are not even online during epoch. 
And this is something what can help people and not to be discriminatory to people who have less power machines.
I don't mind for me this system now is perfect with 16vCPU and 32gbRAM but still we are here to help Idena to make his progress and this way we will have lot of keys for candidates and still make all provides happy. Maybe I'am wrong but this is best what I come with it.
 Any suggestion is okay and I will expect any other opinions regards this meter.
