### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-web#30]
User on TG @hyperattractive

Idena address: https://scan.idena.io/address/0xDee206F974F89D87127b43f11ef7c819BA0F59d6
Used my shared node.

![photo_2021-02-22_14-35-31](https://user-images.githubusercontent.com/37978870/110619088-ac8e8c00-8197-11eb-8fdd-ec9d066e47b3.jpg)

https://user-images.githubusercontent.com/37978870/110619101-b0221300-8197-11eb-9327-a9dddd11f1ff.MP4

**Comment by ridenaio** [comment]
Hi, there was a problem with our shared nodes during this validation. If the problem still exists, please make another issue.
