### ISSUE TITLE
Error while submitting flip: "Expected private key to be an Uint8Array with length 32"

### ISSUE THREAD

**Issue by Spiketr4in** [idena-network/idena-web#36]
An user reported they can't submit flips via web app, as when they click "submit" they get the error: "Expected private key to be an Uint8Array with length 32"

**Details and preliminary tests**
- The same behavior has been observed with 3 different shared nodes
- The user has no issue submitting flips through the desktop client
- The user has already used a shared node without issues to pass the validation as a candidate last epoch, with the same "encrypted private key + password" pair; this is the first time they are required to submit flips.
- Re-exporting the private key with a different password using the desktop client and using the new "encrypted private key + password" pair didn't help

**Comment by ridenaio** [comment]
Fixed in #43
