### ISSUE TITLE
After authorization via idena-web, the browser became unresponsive, displaying a message to stop load the page.

### ISSUE THREAD

**Issue by ltraveler** [idena-network/idena-web#404]
Some people have reported that after authorization, the browser gets stuck after some time, and a message appears asking to stop the page. As a result, many people failed the validation because of this issue.

**Comment by gmilanche** [comment]
I experience this issue on multiple devices and multiple browsers. Tested 3 laptops (Win 10 and Win 11) and 2 phones (Android and Iphone)
 1. Win 10: only Firefox was working, Chrome, Opera, Edge not working
 2. Win 10: only Firefox in private browsing mode working, Chrome, Opera, Edge and regular Firefox not working
 3. Win 11: none working (Chrome, Firefox, Edge, Opera)
 4. Android: Chrome and Firefox tested, not working
 5. Iphone: Safari tested not working.

**Comment by an-trader** [comment]
I had no problem on validation, but after validation the problem appeared.


![image](https://github.com/idena-network/idena-web/assets/87753268/c8328175-1855-4a9a-a685-ae36c1862a4f)

**Comment by hlolve** [comment]
Vercel blocking web app, maybe considering as ddos ?

**Comment by jessidy** [comment]
app.idena.io spam to google analystics 10k per minute requests, that hangs the browser

**Comment by gmilanche** [comment]
> app.idena.io spam to google analystics 10k per minute requests, that hangs the browser

On my 1st laptop, on Firefox, I had AdBlocker installed which block these requests, so web app there worked like a charm.
On rest of my devices and browsers I hadn't any AdBlocker so it failed...

**Comment by hlolve** [comment]
I can login using https://app.idena.io/wallets but can´t if using https://app.idena.io or https://app.idena.io/home

**Comment by ltraveler** [comment]
Some latest facts that we know for the current moment:

1. The app didn't have any changes in comparison to the version that was used in the previous epoch validation, so the problem is definitely not related to any sort of bug on the code side of the web application.
2. It looks like Vercel somehow limited connections due to some reason by regions, which is why some people could pass the validation while others could not.

My question is, would it be possible to run everything related to the web app from IPFS?
Alternatively, could the entire node application encapsulate the web application as well, allowing people in the shared node marketplace apart from API key to get the link to the encapsulated web application on the shared node operator side?

**Comment by hlolve** [comment]
The only way app.idena.io/home is working for me is in incognito mode

**Comment by ltraveler** [comment]
I think the biggest problem, in the case of running the web application on the side of the shared node operators, would be how to verify the web app? I believe the shared node would need to have a mechanism to ensure that the web app has not been changed. For example, it could involve creating and signing a container by the developers, and idena-go would have to check that signature before trusting it and use it as official representation of the web-app.
