### ISSUE TITLE
Unexpected late submission

### ISSUE THREAD

**Issue by DyuldinKS** [idena-network/idena-web#427]
Hello.
Validation on March 30th ended for me and my friend with the status `late submission`, even though all the transactions with short/long session answers have been sent on time.
Addresses:
0x75d6cE9A43A681BD21B79ccB148C07DA65345072
0x052cD56Ec984298E2E4dceCf26410eC964D3554d

I can also attach the log files here if they don't contain any sensitive data.

**Comment by hlolve** [comment]
Did you use web app or desktop app ? If web app, what shared node did you use, private or from marketplace ?
Late submission is not only related to the time answers submitted.

**Comment by hlolve** [comment]
Addresses:
0x75d6cE9A43A681BD21B79ccB148C07DA65345072
0x052cD56Ec984298E2E4dceCf26410eC964D3554d

In the case of both addresses, the late submission is related to created flips were not available on time for validation, decryption keys didn't reach on time the network.

**Comment by DyuldinKS** [comment]
Thanks for the answer.
> Did you use web app or desktop app ?
Web app, the node is private.
> decryption keys didn't reach on time the network.
What are decryption keys? Should they be transmitted from client to the shared node?
Is it possible to definitely say whether the problem was in the shared node or in the clients’ network?

**Comment by hlolve** [comment]
> Is it possible to definitely say whether the problem was in the shared node or in the clients’ network?

Is possible if you have logs from client and from shared node to check

**Comment by DyuldinKS** [comment]
While I was discussing uploading and sending logs with the owner of the shared node, they were overwritten with more recent ones. And we don’t have logs from the last validation.

Btw is there a method to check if the flips are available for the next validation (before the validation)?
Maybe some node API call?

**Comment by hlolve** [comment]
Flips are available as soon are submitted, you can check in scan.idena.io but encrypted for all the network, and only decrypted at ceremony time, when ID that created the flips send keys to decrypt

**Comment by DyuldinKS** [comment]
Now I got it - the issue is about delivering the decryption key, not the flips themselves.
Thank you for the info, I'm closing the issue.
