### ISSUE TITLE
Renaming invitee under contacts loses connection to that invitee

### ISSUE THREAD

**Issue by pocoloko** [idena-network/idena-web#91]
I created an invitation, invitee accepted and status was shown as Candidate under contacts in web app.
After this I renamed the contact, and now the status shows up as in the screenshot:

![image](https://user-images.githubusercontent.com/65197321/128641205-024680ee-278f-46ec-aa9b-57169e5962e1.png)

I looked in the IdenaStore Indexed DB in Firefox, and this particular entry no longer has the hash, receiver, key, activated, etc values that a regular invitee has:

![image](https://user-images.githubusercontent.com/65197321/128641355-0a18c74b-9d79-48b2-85aa-5d55e9cbe064.png)

it appears this data was lost during the rename, please fix :)

**Comment by aidenaio** [comment]
should be fixed in #142
